#!/usr/bin/env python3
"""
Zoth Model Transparency Exposer & Audit Tool
Generates a complete transparency manifest (zoth_ai_transparency_report.json / .md)
documenting base architecture, parameters, SHA256 hashes, dataset inputs, and system prompt.
"""

import json
import hashlib
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DATASET_FILE = REPO_ROOT / "zoth_training_dataset.jsonl"
MODELFILE = REPO_ROOT / "Modelfile.zoth"
TRANSPARENCY_JSON = REPO_ROOT / "zoth_ai_transparency_report.json"
TRANSPARENCY_MD = REPO_ROOT / "zoth_ai_transparency_report.md"

def get_file_sha256(filepath: Path) -> str:
    if not filepath.exists():
        return "N/A"
    hasher = hashlib.sha256()
    with open(filepath, "rb") as f:
        while chunk := f.read(8192):
            hasher.update(chunk)
    return hasher.hexdigest()

def get_ollama_show():
    try:
        res = subprocess.run(["ollama", "show", "zoth-ai:latest"], capture_output=True, text=True)
        return res.stdout
    except Exception as e:
        return str(e)

def generate_transparency_report():
    dataset_hash = get_file_sha256(DATASET_FILE)
    modelfile_hash = get_file_sha256(MODELFILE)
    ollama_details = get_ollama_show()

    # Load dataset sample info
    dataset_count = 0
    if DATASET_FILE.exists():
        with open(DATASET_FILE, "r", encoding="utf-8") as f:
            dataset_count = sum(1 for _ in f)

    report_data = {
        "model_name": "zoth-ai:latest",
        "base_model": "Qwen2.5-Coder 1.5B (Quantized Q4_K_M)",
        "quantization": "4-bit (Q4_K_M)",
        "parameter_count": "1.5 Billion Parameters",
        "context_length": 32768,
        "embedding_length": 1536,
        "transparency_verification": {
            "dataset_sha256": dataset_hash,
            "modelfile_sha256": modelfile_hash,
            "dataset_filepath": str(DATASET_FILE),
            "modelfile_filepath": str(MODELFILE),
            "training_samples_count": dataset_count
        },
        "system_configuration": {
            "temperature": 0.2,
            "top_p": 0.9,
            "stop_tokens": ["<|im_end|>", "<|endoftext|>"]
        },
        "ollama_inspection_output": ollama_details
    }

    # Write JSON
    with open(TRANSPARENCY_JSON, "w", encoding="utf-8") as f:
        json.dump(report_data, f, indent=2)

    # Write Human-Readable Markdown
    md_content = f"""# 🔍 Zoth-AI Model Transparency & Open Weights Audit Report

This document provides full transparency into the **`zoth-ai:latest`** local artificial intelligence model.

---

## 🏛️ Model Specifications & Architecture

| Property | Value |
|---|---|
| **Model Name** | `zoth-ai:latest` |
| **Base Weights** | `qwen2.5-coder:1.5b` (Qwen 2.5 Architecture) |
| **Parameter Count** | 1.5 Billion Parameters |
| **Quantization Format** | GGUF Q4_K_M (4-bit Medium Quantization) |
| **Context Window** | 32,768 tokens |
| **Embedding Dimension** | 1,536 |
| **License** | Apache 2.0 (Open Weights) |

---

## 🔒 Cryptographic Verification Hashes (SHA-256)

Every artifact used to create `zoth-ai:latest` is verifiable locally:

* **Training Dataset SHA256**:  
  `{dataset_hash}`  
  *Path*: [`zoth_training_dataset.jsonl`](file://{DATASET_FILE}) ({dataset_count} instruction pairs)

* **Ollama Modelfile SHA256**:  
  `{modelfile_hash}`  
  *Path*: [`Modelfile.zoth`](file://{MODELFILE})

---

## ⚙️ Model Hyperparameters & Controls

* **Temperature**: `0.2` (Low temperature for precise, non-hallucinating code/system generation)
* **Top-P**: `0.9`
* **Stop Tokens**: `<|im_end|>`, `<|endoftext|>`

---

## 📊 Complete Ollama Model Inspection Output

```
{ollama_details.strip()}
```

---

*Report automatically generated by Zoth Studio Transparency Engine.*
"""

    with open(TRANSPARENCY_MD, "w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"[+] Transparency JSON generated: {TRANSPARENCY_JSON}")
    print(f"[+] Transparency Markdown report generated: {TRANSPARENCY_MD}")

if __name__ == "__main__":
    generate_transparency_report()
